Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.hostname = "grup04.fjeclot.net"
  config.vm.provider "virtualbox" do |v|
    # v.gui = true
    v.name = "grup04"
    v.memory = 2048
    v.cpus = 2
    v.customize ['modifyvm', :id, '--clipboard', 'bidirectional','--groups','/ASIX2']
  end

  config.vm.network "forwarded_port", guest: 80, host: 8000
  config.vm.network "forwarded_port", guest: 443, host: 8443

  config.vm.synced_folder "../codi_projectes", "/home/vagrant/projectes"

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update -y
    # sudo apt-get upgrade -y
    sudo apt-get install -y aptitude net-tools
	sudo apt-get install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common
	sudo curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add
	sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
	sudo apt-get -y update
	sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose
  SHELL

end
